NET-224 Investigate authentication issues with JWT
Vladacdc/TransIT.API pull request #11
Opened 2019-07-13 16:30 UTC by andriyshevchenko

- Updated access token lifetime, because it was equal to 5 minutes
- Avoid adding duplicate tokens to database.

2019-07-13 16:36 UTC, BohdanBuhrii submitted a review, later dismissed

2019-07-14 22:05 UTC, Vladacdc requested changes
Always getting an exception on authentication. 

> Source sequence contains more than one element.

Line 54-55 AuthenticationService.cs

2019-07-14 22:34 UTC, Vladacdc commented
Everything works if i change _SingleOrDefaultAsync_ to _FirstOrDefaultAsync_.  Line 29 BaseRepository.cs
`public virtual Task<TEntity> FindAsync(Expression<Func<TEntity, bool>> predicate)
        {
            return ComplexEntities.FirstOrDefaultAsync(predicate);
            //return ComplexEntities.SingleOrDefaultAsync(predicate);
        }`

2019-07-15 04:31 UTC, igolovchuk approved these changes

2019-07-15 05:20 UTC, Vladacdc approved these changes

2019-07-15 11:11 UTC, BohdanBuhrii approved these changes

2019-07-15 11:12 UTC, merged