update AuthenticationService test
Vladacdc/TransIT.API pull request #25
Opened 2019-07-31 16:38 UTC by andriyshevchenko

Updated AuthTests, so now it's using only mock objects

2019-07-31 17:20 UTC, igolovchuk requested changes
- please move initialization logic for dependencies into separate private methods and use them in the constructor
- mark in all tests its parts using comments and AAA signature(// Arrange. // Act .// Assert.
and add empty lines between the parts
- use 'var' keyword when initialize some instance  eg. var service = new AuthServcie...
- remove 'partial' from class if it is not needed

2019-07-31 20:10 UTC, andriyshevchenko commented
Should i use .Verify() methods after assertion to check if certain methods were called?

2019-08-01 04:39 UTC, igolovchuk approved these changes

2019-08-01 12:38 UTC, SviatoslavBachynskyi approved these changes

2019-08-01 12:50 UTC, merged