feature/2019.07.11_NET-219_Vladyslav_Rohov
Vladacdc/TransIT.API pull request #4
Opened 2019-07-11 20:08 UTC by Vladacdc

2019-07-12 04:30 UTC, igolovchuk requested changes
- do not name pull request as a branch name
- remove one of the testing frameworks means not just remove it and all related files, you should remove lib from the project, add lib that you will use and rewrite all tests to use that lib

2019-07-12 18:39 UTC, Vladacdc commented
@igolovchuk 
> ...rewrite all tests to use that lib
I have to rewrite them using DTO? 
If yes, then this task is blocked by  #6

2019-07-13 06:31 UTC, igolovchuk commented
> @igolovchuk
> 
> > ...rewrite all tests to use that.
> 
> I have to rewrite them using DTO?
> If yes, then this task is blocked by #6

For now, you can commit as it was(without DTO), the task #6 owner will fix tests before megre in his pull request

2019-07-16 04:24 UTC, igolovchuk commented on TransIT.BLL.Tests/Services/CrudServiceTests.cs
> +                _repository.Verify(r => r.AddAsync(entity), Times.Once);
- try to use framework for thism eg.  
```
// act & assert
    Assert.Throws<Exception>(async () => await _crudService.CreateAsync(entity));
   _repository.Verify(r => r.AddAsync(entity), Times.Once);
    VerifyLogger();
```

2019-07-16 04:26 UTC, igolovchuk commented on TransIT.BLL.Tests/Services/CrudServiceTests.cs
> +            }
- the same here, try to use framework for this, ex. look in the previous comment

2019-07-16 04:28 UTC, igolovchuk commented on TransIT.BLL.Tests/Services/ImplementedServices/CountryServiceTests.cs
> +    class CountryServiceTests : CrudServiceTest<Country>
add modifier

2019-07-16 04:28 UTC, igolovchuk commented on TransIT.BLL.Tests/Services/ImplementedServices/SupplierServiceTests.cs
> +    class SupplierServiceTests : CrudServiceTest<Supplier>
add modifier

2019-07-16 04:28 UTC, igolovchuk commented on TransIT.BLL.Tests/Services/ImplementedServices/CurrencyServiceTests.cs
> +    class CurrencyServiceTests : CrudServiceTest<Currency>
add modifier

2019-07-16 04:29 UTC, igolovchuk requested changes
- see comments

2019-07-16 12:40 UTC, igolovchuk approved these changes

2019-07-16 12:42 UTC, BohdanBuhrii approved these changes

2019-07-16 12:42 UTC, VitaliiMaksymiv approved these changes

2019-07-16 12:42 UTC, merged