Feature/14.08.2019_TNT794_Register_MyIssues_Maksymiv
Vladacdc/TransIT.API pull request #45
Opened 2019-08-14 23:54 UTC by VitaliiMaksymiv

2019-08-15 00:26 UTC, andriyshevchenko submitted a review, later dismissed
Molodec

2019-08-15 04:28 UTC, igolovchuk commented on TransIT.API/Controllers/IssueController.cs
> +                    (model.Filters?.Count > 1
.Any() == Count > 0, so you can remove .Any() check

2019-08-15 04:28 UTC, igolovchuk commented on TransIT.API/Controllers/IssueController.cs
> +                    || (model.Search != null
replace with just !string.IsNullOrEmty(model.Search?.Value)

2019-08-15 11:24 UTC, BohdanBuhrii submitted a review, later dismissed

2019-08-15 11:29 UTC, andriyshevchenko approved these changes

2019-08-15 11:30 UTC, andriyshevchenko submitted a review, later dismissed

2019-08-15 11:35 UTC, SviatoslavBachynskyi submitted a review, later dismissed

2019-08-15 11:56 UTC, igolovchuk commented on TransIT.API/Controllers/IssueController.cs
> +                    || (!string.IsNullOrEmpty(model.Search.Value))
model.Search**?.**Value

2019-08-15 11:59 UTC, igolovchuk requested changes
you missed null check

2019-08-15 12:05 UTC, igolovchuk approved these changes

2019-08-15 12:05 UTC, andriyshevchenko approved these changes

2019-08-16 07:42 UTC, BohdanBuhrii approved these changes

2019-08-16 21:07 UTC, merged