Added Tests to Unit & Manufacturer
Vladacdc/TransIT.API pull request #52
Opened 2019-08-21 14:50 UTC by Vladacdc

2019-08-21 15:24 UTC, andriyshevchenko submitted a review, later dismissed

2019-08-21 15:30 UTC, VitaliiMaksymiv submitted a review, later dismissed

2019-08-21 18:12 UTC, igolovchuk commented on TransIT.BLL/Services/ImplementedServices/ManufacturerService.cs
> +                    .Select(x => x.Trim().ToUpperInvariant())
use SearchTokenCollection from after pull request #50 will be merged

2019-08-21 18:13 UTC, igolovchuk commented on TransIT.BLL/Services/ImplementedServices/UnitService.cs
> +                    .Split(new[] { ' ', ',', '.' }, StringSplitOptions.RemoveEmptyEntries)
use SearchTokenCollection class as searchexpressionasync input after pull request #50 will be merged

2019-08-21 18:19 UTC, igolovchuk requested changes
please make changes described in comments

2019-08-22 13:05 UTC, Vladacdc commented
> 
> 
> Manufacturer Of Work?

Ups, Ctrl+H ))

2019-08-22 13:48 UTC, andriyshevchenko approved these changes

2019-08-23 04:25 UTC, igolovchuk approved these changes

2019-08-23 06:53 UTC, andriyshevchenko approved these changes

2019-08-23 08:06 UTC, BohdanBuhrii approved these changes

2019-08-23 08:21 UTC, merged