Added Work Types to backend
Vladacdc/TransIT.API pull request #53
Opened 2019-08-22 10:38 UTC by VitalikRibiy

2019-08-22 10:40 UTC, BohdanBuhrii submitted a review, later dismissed

2019-08-22 11:13 UTC, andriyshevchenko submitted a review, later dismissed

2019-08-22 12:19 UTC, igolovchuk commented on TransIT.DAL/Repositories/ImplementedRepositories/WorkTypeRepository.cs
> +        public override Task<IQueryable<WorkType>> SearchExpressionAsync(IEnumerable<string> strArr)
as I remember in pull request #50 SearchExpressionAsync was removed so please merge with latest dev and use the same approach as was done there

2019-08-22 12:20 UTC, igolovchuk commented on TransIT.BLL/Services/ImplementedServices/WorkTypeService.cs
> +                    .Split(new[] { ' ', ',', '.' }, StringSplitOptions.RemoveEmptyEntries)
please merge with the latest dev and use the same approach as was done there(use SearchTokenCollection)

2019-08-22 12:21 UTC, igolovchuk requested changes
please read comments in files

2019-08-23 02:37 UTC, Vladacdc requested changes
Please look at comments and try to resolve those issues.

2019-08-23 02:37 UTC, Vladacdc commented on TransIT.DAL/Models/Entities/WorkType.cs
> +        {
So you initializing `ICollection ` in User, but not here. Please, initialize `ICollection `

2019-08-23 02:37 UTC, Vladacdc commented on TransIT.DAL/Models/EntityConfiguration/WorkTypeConfiguration.cs
> +            builder.HasIndex(e => e.Id)
Change this to primary key, which by default unique.

2019-08-23 02:37 UTC, Vladacdc commented on TransIT.DAL/Models/EntityConfiguration/WorkTypeConfiguration.cs
> +            builder.Property(e => e.CreatedById).HasColumnName("CREATE_ID");
btw why all of you adding such column names? (just a question)

2019-08-23 02:37 UTC, Vladacdc commented on TransIT.DAL/Repositories/ImplementedRepositories/IssueLogRepository.cs
> +            .Include(w=>w.WorkType)
Please style your code properly, at least spacing.

2019-08-23 02:37 UTC, Vladacdc commented on TransIT.DAL/Repositories/ImplementedRepositories/WorkTypeRepository.cs
> +            return part => EF.Functions.Like(part.Name, '%' + keyword + '%');
It would be nice to add filtering not only by name, but also by `EstimatedCost` and `EstimatedTime`

2019-08-23 02:46 UTC, Vladacdc commented on TransIT.DAL/Repositories/ImplementedRepositories/WorkTypeRepository.cs
> +            return part => EF.Functions.Like(part.Name, '%' + keyword + '%');
btw look at `PartRepository` and add more filtering if you can or ask someone to do that. 
Nice example is `IssueRepository`, look how its done there.

2019-08-23 04:24 UTC, igolovchuk submitted a review, later dismissed

2019-08-23 06:53 UTC, andriyshevchenko submitted a review, later dismissed

2019-08-23 09:12 UTC, konerokua approved these changes

2019-08-23 09:27 UTC, Vladacdc approved these changes

2019-08-23 09:29 UTC, BohdanBuhrii approved these changes

2019-08-23 09:31 UTC, merged